version: '3'
services:
  web:
    image: python:3.9
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - /app
    command: >
      sh -c "apt-get update && apt-get install -y git &&
             git clone https://github.com/HAOYUAN521/DeepLost_Docker.git /app &&
             pip install -r /app/requirements.txt &&
             python /app/app.py"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
